### ISSUE TITLE
Référence à du JS non présent dans core/template

### ISSUE THREAD

**Issue by Gis70** [mika-nt28/Jeedom-Freebox_OS#10]
Salut, dans les fichiers suivants : 
![image](https://user-images.githubusercontent.com/16589132/68858071-7dbbef00-06e4-11ea-8125-ee89d1e78744.png)

Il y est fait référence à maphilight.min.js qui serait dans le plugin motion.

![image](https://user-images.githubusercontent.com/16589132/68858155-b5c33200-06e4-11ea-8a85-91d6348628a0.png)

Si c'est nécessaire, peux tu le mettre dans ce plugin et / ou corriger ? merci.

**Comment by mika-nt28** [comment]
Effectivement un malheureux copier coller
J'ai poussé la mise a jours sur le market
