### ISSUE TITLE
Sens ouverture volet somfy

### ISSUE THREAD

**Issue by johnbartx** [mika-nt28/Jeedom-Freebox_OS#111]
Bonjour, est il possible de nous donne la possibilité d'inverser le sens d'ouverture des volets Somfy

Je m'explique aujourd'hui il faut mettre sur 100 pour un volet complètement fermé et 0 sur complètement ouvert, mais une fois sur Homebridge pour homekit 100 c'est pour lui ouvert (et non fermé) et 0 ferme (et non ouvert) ^^

Ce serai genial merci ^^

**Comment by mika-nt28** [comment]
Non ce n'est pas possible vue la complexité du plugin
