### ISSUE TITLE
Affichage

### ISSUE THREAD

**Issue by dams74** [mika-nt28/Jeedom-Freebox_OS#18]
Bonjour Mika
Je me sers de ton plugin qui est vraiment génial.
Jusque maintenant je n'avais pas changé de thème sur mon jeedom.
En ce moment j'ai le thème Dark unica et le bouton  de mise en veille de la télécommande n'affiche plus la couleur rouge quand elle est allumé.
Sais tu d'où peux provenir ce problème?
Merci
Damien

**Comment by mika-nt28** [comment]
Certainement d'un conflie de nom dans les class

**Comment by mika-nt28** [comment]
J'ai corriger le problème.
le theme utilisée force le backgroud-color sur le btn-defaut
