### ISSUE TITLE
[Feature request] Wake on LAN

### ISSUE THREAD

**Issue by wikijm** [mika-nt28/Jeedom-Freebox_OS#187]
Hello @mika-nt28,

I'm wondering if you could add the Wake on LAN functionality?
I assume that you have to use information visible here: https://dev.freebox.fr/sdk/os/lan/

Thanks for your wonderful job!

**Comment by JEALG** [comment]
Hello

Merci de passer par community pour les améliorations plus facile a gérer

**Comment by JEALG** [comment]
Elle est disponible via le widget du réseau cela ouvre une modale

**Comment by wikijm** [comment]
> 
> 
> Elle est disponible via le widget du réseau cela ouvre une modale

Hélas, cela ne fonctionne pas pour mon installation (paquet WOL non visible avec Wireshark, alors que c'est bien le cas avec l'application mobile Freebox Companion, ainsi qu'avec la commande Linux `wakeonlan`).

J'ai fini par utiliser le plugin 'Script' pour lancer la commande `wakeonlan XX:XX:XX:XX:XX:XX`.

Merci d'avoir pris le temps de m'avoir répondu 😉

**Comment by JEALG** [comment]
Hello
Peut tu ouvrir un sujet sur communauty pour que l on puisse voir ce qu'il te faut et surtout bien d'écrire ta demande

Et montrer un exemple comment tu as fait 

On pourra alors voir si on peut l intégrer 

Merci
