### ISSUE TITLE
Problème avec Satut power

### ISSUE THREAD

**Issue by dams74** [mika-nt28/Jeedom-Freebox_OS#22]
Lorsque je démarre ma freebox player, j'ai un scénario qui détecte le status power et qui lance mon ampli.
Depuis quelque jours ça fonctionne mal, des fois ça démarre l'ampli au bout de 30 s des fois c'est plusieurs minutes...
Avez-vous remarqué ce problème?
Je viens de regarder dans le plugin, je n'y était pas allé depuis un moment car fonctionnel et je n'ai rien qui s'affiche lorsque je clique sur paramètre freebox.
Est-ce normal?
merci
Damien

**Comment by mika-nt28** [comment]
C'est que tu as un problème sur ton installation car chez moi tous fonctionnent.
