### ISSUE TITLE
Interference with weather and Freebox plugin

### ISSUE THREAD

**Issue by Pierre55555** [mika-nt28/Jeedom-Freebox_OS#27]
Bonjour,

Le WE dernier, j'ai fait une mise à jour sur ma Smat Zwave comme d'habitude, et j'ai constaté un emballement du CPU, et le passage de ma mémoire de stockage à 100%.
Après avoir pendant une heure tenté de récupérer les choses, je me suis résolu à faire une restauration Jeedom qui heureusement a fonctionné.
Les messages que j'avais avant la restauration disaient que cron weather n'avait pas fini sa tâche.
Mais en regardant avec lsof, j'ai trouvé des fichiers de 690 Mo, comme montré ci-dessous, et le pid correspondant semble pointer vers le plugins freebox.
Je ne suis pas du tout expert Linux, mais maintenant, je n'ose plus faire de mise à jour de peur de planter encore ma box Jeedom.

`root@jeedom:/var/www/html/log# lsof | grep deleted
COMMAND     PID   TID       USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME

[... many lines ...]

python     1852  1900   www-data    3w      REG              179,7     12858     137958 /var/www/html/log/openzwaved (deleted)
python     1852  1900   www-data    4u      REG              179,7      8192     167185 /var/www/html/plugins/openzwave/data/pyozw.sqlite (deleted)
python     1852 24312   www-data    1w      REG              179,7      1280     137927 /var/www/html/log/openzwave (deleted)
python     1852 24312   www-data    2w      REG              179,7      1280     137927 /var/www/html/log/openzwave (deleted)
python     1852 24312   www-data    3w      REG              179,7     12858     137958 /var/www/html/log/openzwaved (deleted)
python     1852 24312   www-data    4u      REG              179,7      8192     167185 /var/www/html/plugins/openzwave/data/pyozw.sqlite (deleted)
php        9642         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9642         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9642         www-data    4ur     REG               0,34         0     103086 /tmp/.ZendSem.bpsrch (deleted)
php        9727         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    4ur     REG               0,34         0     103162 /tmp/.ZendSem.FNHk51 (deleted)
apache2   11328         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
php       12675         www-data    4ur     REG               0,34         0    1253871 /tmp/.ZendSem.Rqxe9x (deleted)
apache2   14946         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   17735         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   17756         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   19671         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   22524         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
php       22777         www-data    4ur     REG               0,34         0    3497905 /tmp/.ZendSem.xcsq2Q (deleted)
apache2   23545         www-data    8ur     REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   25940         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   28589         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   28598         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   32022         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)

root@jeedom:/var/www/html/log# lsof | grep cron_execution
php        9642         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9642         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php       12675         www-data    1w      REG              179,7     13114     133447 /var/www/html/log/cron_execution
php       12675         www-data    2w      REG              179,7     13114     133447 /var/www/html/log/cron_execution

root@jeedom:/var/www/html/log# cat /proc/9642/fd/1
[... Many lines...]
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/Freebox_OS/core/class/Freebox_OS.class.php on line 578
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/Freebox_OS/core/class/Freebox_OS.class.php on line 578
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/Freebox_OS/core/class/Freebox_OS.class.php on line 578
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/^C
root@jeedom:/var/www/html/log#
`

**Comment by Pierre55555** [comment]
Je me rends compte que la mise en page de la sortie console ssh n'est pas bien passée, je rééssaie avec des guillemets:

> root@jeedom:/var/www/html/log# lsof | grep deleted
COMMAND     PID   TID       USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME

[... many lines ...]

python     1852  1900   www-data    3w      REG              179,7     12858     137958 /var/www/html/log/openzwaved (deleted)
python     1852  1900   www-data    4u      REG              179,7      8192     167185 /var/www/html/plugins/openzwave/data/pyozw.sqlite (deleted)
python     1852 24312   www-data    1w      REG              179,7      1280     137927 /var/www/html/log/openzwave (deleted)
python     1852 24312   www-data    2w      REG              179,7      1280     137927 /var/www/html/log/openzwave (deleted)
python     1852 24312   www-data    3w      REG              179,7     12858     137958 /var/www/html/log/openzwaved (deleted)
python     1852 24312   www-data    4u      REG              179,7      8192     167185 /var/www/html/plugins/openzwave/data/pyozw.sqlite (deleted)
php        9642         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9642         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9642         www-data    4ur     REG               0,34         0     103086 /tmp/.ZendSem.bpsrch (deleted)
php        9727         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    4ur     REG               0,34         0     103162 /tmp/.ZendSem.FNHk51 (deleted)
apache2   11328         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
php       12675         www-data    4ur     REG               0,34         0    1253871 /tmp/.ZendSem.Rqxe9x (deleted)
apache2   14946         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   17735         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   17756         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   19671         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   22524         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
php       22777         www-data    4ur     REG               0,34         0    3497905 /tmp/.ZendSem.xcsq2Q (deleted)
apache2   23545         www-data    8ur     REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   25940         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   28589         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   28598         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)
apache2   32022         www-data    8u      REG               0,34         0      15014 /tmp/.ZendSem.ikKlOc (deleted)

root@jeedom:/var/www/html/log# lsof | grep cron_execution
php        9642         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9642         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    1w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php        9727         www-data    2w      REG              179,7 695098087     132326 /var/www/html/log/cron_execution (deleted)
php       12675         www-data    1w      REG              179,7     13114     133447 /var/www/html/log/cron_execution
php       12675         www-data    2w      REG              179,7     13114     133447 /var/www/html/log/cron_execution



root@jeedom:/var/www/html/log# cat /proc/9642/fd/1
[... Many lines...]
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/Freebox_OS/core/class/Freebox_OS.class.php on line 578
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/Freebox_OS/core/class/Freebox_OS.class.php on line 578
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/Freebox_OS/core/class/Freebox_OS.class.php on line 578
PHP Warning:  sleep() expects parameter 1 to be integer, string given in /var/www/html/plugins/^C
root@jeedom:/var/www/html/log#

**Comment by mika-nt28** [comment]
Le support se fait sur community

**Comment by mika-nt28** [comment]
Bonjour

Si cpu plein charge,
Assurez vous que la migration du temps de boucle c'est bien reporté sur chaque équipement du plugin freebox_OS


Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Pierre55555** [comment]
Merci,
J'ai vu en effet sur Community que le plugins avait été mis à jour.
Ce plugin est génial, un gros gros gros merci pour l'avoir écrit, c'est trop bien pour Jeedom.

Sinon, j'ai écrit sur github parce que par defaut la demande d'assistance créé dans l'interface Jeedom m'a envoyé sur Github.
Pour info, je viens de faire la MAJ à l'instant, et j'ai encore un soucis avec un message "Class Freebox_OS does not exist"
