### ISSUE TITLE
Message Jeedom : Expression cron non valide pour [XXX][Système] : */30 * * * *

### ISSUE THREAD

**Issue by dawstudiocenter** [mika-nt28/Jeedom-Freebox_OS#308]
Bonjour,
J'ai régulièrement le message d'erreur jeedom suivant :

`Expression cron non valide pour [Infrastructure][Système] : */30 * * * * `

Sur cette base de configuration du plugin pour ma freebox revolution :
![image](https://user-images.githubusercontent.com/6443323/95648242-f59dbf80-0ad5-11eb-98af-217e2223f2cb.png)

![image](https://user-images.githubusercontent.com/6443323/95648206-be2f1300-0ad5-11eb-8a18-3c4b346e0926.png)
![image](https://user-images.githubusercontent.com/6443323/95648219-d2731000-0ad5-11eb-9666-3c6806ff9670.png)

![image](https://user-images.githubusercontent.com/6443323/95648188-98a20980-0ad5-11eb-979b-97c928df9992.png)

J'ai beau changé la valeur du cron, j'ai toujours le message.

**Comment by JEALG** [comment]
Hello
Merci de passer par le forum et non par ici.
