### ISSUE TITLE
Impossible d'appairer

### ISSUE THREAD

**Issue by mmorier** [mika-nt28/Jeedom-Freebox_OS#44]
Bonjour,

Dès que je souhaite faire l'appairage avec la Freebox, j'obtiens le message d'erreur `erreur interne`. Tout semble s'être bien passé à l'installation, je n'ai aucun log ou message d'erreur en ce sens.
Si je modifie l'adresse IP, j'ai bien une erreur 404.
Si j'interdis l'association de nouveaux appareils coté Freebox, j'ai bien un message d'erreur m'indiquant où rétablir ce paramètre.
Aucune idée d'où le problème peut venir car je n'ai aucun log même en debug.
J'ai redémarré Jeedom mais c'est pareil.

Ci-joint, une capture d'écran après avoir cliqué sur le bouton Appairage.
![image](https://user-images.githubusercontent.com/666997/46914873-9f0f5080-cfa3-11e8-9ca7-1c9fac10439d.png)

Une idée du problème ?

**Comment by mika-nt28** [comment]
Pas de log dans le http error
