### ISSUE TITLE
Compatibilité Freebox OS 4.4

### ISSUE THREAD

**Issue by Pimous972** [mika-nt28/Jeedom-Freebox_OS#563]
Bonjour,

Depuis peu le démon freebox ne veut plus démarrer. 
A priori depuis la mise à jour en freebox OS 4.4.

Est-ce un dysfonctionnement connu?

**Comment by JEALG** [comment]
Bonjour
Merci de passer par communauty et fournir les logs
Aucun soucis avec la mise à jour. A moins que je n'ai pas eu le retour
