### ISSUE TITLE
Fonction HTMLtoXY dans la class Free_Color

### ISSUE THREAD

**Issue by Jeandhom** [mika-nt28/Jeedom-Freebox_OS#605]
La variable $color et l'array éponyme semblent se télescoper dans cette fonction.
J'ai remplacé la variable $color par $_color pour que cela fonctionne.

`public static function HTMLtoXY($_color)
{

	$_color = str_replace('0x', '', $_color);
	$_color = str_replace('#', '', $_color);
	$red = hexdec(substr($_color, 0, 2));
	$green = hexdec(substr($_color, 2, 2));
	$blue = hexdec(substr($_color, 4, 2));
`

**Comment by JEALG** [comment]
ta modification sera intégré mais pour rappel elle n'est pas appelé par le code actuellement

**Comment by Jeandhom** [comment]
Merci JAG.
Ceux qui veulent appeler ta fonction dans leur code seront heureux de ne pas tomber sur une fonction buggé.
