### ISSUE TITLE
affichage sans toutes les actions

### ISSUE THREAD

**Issue by loopingcooper** [mika-nt28/Jeedom-Freebox_OS#81]
Salut,
j'ai le plugin installé sur mon jeedom depuis un peu plus d'un an, et j'ai voulu commencer à me faire un dashbord plus propre.
Donc, dans l'équipement ADSL, j'ai voulu masquer certaines infos qui ne m'intéressent pas (en fait, ne garder affiché que la vitesse de synchro.  Le résultat n'est pas vraiment ce que j'espérais....
<img width="204" alt="Capture d’écran 2019-08-18 à 14 56 30" src="https://user-images.githubusercontent.com/34935262/63224728-a0fbfe80-c1c8-11e9-842f-cc8ab2af60d2.png">

**Comment by mika-nt28** [comment]
Oui je vois le probleme 
Si la commande est masqué elle n'est pas remplacé du coup le widget ne se met pas completement a jours.
Je regarde ca pour une prochaine release

**Comment by loopingcooper** [comment]
Ah, pas passé dans celle d'aujourd'hui? :)

**Comment by mika-nt28** [comment]
Toujours la me chose?
Tu es en V4?

**Comment by loopingcooper** [comment]
toujours la même chose! je suis sur la dernière version stable en V3.3 .31

Un interet à passer en V4 ?

**Comment by mika-nt28** [comment]
En fait pour le moment je rend la compatibilité avec la V4
Et dans la V4 les widget sont integrer au core et si j'adopte le systeme pour ne plus maintenir des widget plugin le plugin sera obligatoirement compatible V4

Tres sincèrement je me pose de plus en plus la question de supprimer tous les template qui laisserai plus de souplesse  a la personnalisation et m’éviterai un maximum de maintenance a chaque mise a jours du core de jeedom

**Comment by loopingcooper** [comment]
OK je comprend mieux.  Perso la V4 m'ennuie à cause de ca.. ils reprennent les widget... mais ils n'en assuraient déjà pas la compatibilité avec la V3 ... et certains ne sont pas que juste des images.. du coup ca va etre un beau bordel ! (par exemple , j'ai du texte défilant...... ) 

Pour la partie personnalisation.... je suis complètement en phase avec toi ;)

**Comment by mika-nt28** [comment]
Oui la migration V3 => V4 est problématique esthétiquement.
Il est toujours possible de cree ses propre widget d'une maniere plus simple car on ne gere que des icone / image.
Le core embarque des template de widget mainenue par le core pour assuré une compatibilité sur toutes les prochaines version
Les anciens widget fonctionne toujours, perso je suis en v4 et les widget du plugin fonctionne, mais il ne sont pas optimum et cela peut provoqué des ralentissement d'affichage des etat.

C'est pour cela que de plus en plus je me pose la question de est tres utile de me faire mal a maintenir des widgets sachant que cela peut provoqué chez tous le monde des ralentissement.
C'est cette meme reflexion qui a amené la V4 il me semble

**Comment by loopingcooper** [comment]
Salut! 
Vu le nombre de widget que j'ai on va oublier la V4 alors!!!!  

j'ai toujours le probleme avec les infos que je ne souhaite pas afficher (exempel STATE ci dessous)
J'ai également remarqué qu'il manque l'unité pour le debit down:

![image](https://user-images.githubusercontent.com/34935262/65686774-4b87fc80-e066-11e9-9cb4-739a3da2d2b8.png)
