### ISSUE TITLE
Mauvaise comparaison dans la création des listes d'appels

### ISSUE THREAD

**Issue by tcalmant** [mika-nt28/Jeedom-Freebox_OS#848]
Bonjour,

Petite typo trouvée: les comparaisons devraient être `== NULL` au lieu de `!= NULL` pour générer la liste des appels reçus
https://github.com/mika-nt28/Jeedom-Freebox_OS/blob/59080e985b33b608563264dbdd0a07ea61580247/core/class/Free_API.class.php#L739
et les appels émis
https://github.com/mika-nt28/Jeedom-Freebox_OS/blob/59080e985b33b608563264dbdd0a07ea61580247/core/class/Free_API.class.php#L748

Pas de problème avec la liste des appels manqués
https://github.com/mika-nt28/Jeedom-Freebox_OS/blob/59080e985b33b608563264dbdd0a07ea61580247/core/class/Free_API.class.php#L730

**Comment by JEALG** [comment]
merci pour le retour
ce bug ne doit pas dater de maintenant, c'est corrigé
par contre merci de passer par communauty, c'est plus facile a suivre pour moi
ce sera disponible demain dans la beta
