### ISSUE TITLE
Evolution : Wifi invité

### ISSUE THREAD

**Issue by CyrilCharlier** [mika-nt28/Jeedom-Freebox_OS#86]
Bonjour,

Superbe plugin merci. Serait-il envisageable de mettre en place l'activation/désactivation du wifi invité ?

merci,

**Comment by mika-nt28** [comment]
Je sais pas si c'est disponible sur l'api.
Je regarderai

**Comment by mika-nt28** [comment]
L'api n'est pas encore reseigné visiblement sous ma box

**Comment by Tom147285** [comment]
Bonjour,
Excellent plugin, merci. Est-il possible d'apporter une amélioration sur les équipements? Plus concrètement, est ce qu'il est possible d'avoir le contrôle parental?
Merci 👍

**Comment by mika-nt28** [comment]
J'ai regardé les api de free et je n'ai pas trouvé comment autorisé ou non un appareil particuler
Mise a part les liste blanche et noire

**Comment by CyrilCharlier** [comment]
Bonjour
Merci d'avoir pris le temps d'y regarder.
bonne continuation
