### ISSUE TITLE
Commande de volets roulants

### ISSUE THREAD

**Issue by durdur45** [mika-nt28/Jeedom-Freebox_OS#87]
Salut Mika,

Sur le forum nous avons évoqué un problème avec les tiles concernant les volets roulant ou les fenêtres par exemple. En fait tout ce qui concerne les tiles d'action "store_slider" dans l'API v6.

Le fait est que les "consigne d'ouverture" sont remontées correctement mais uniquement en info et il n'y a pas de commande d'action créée pour les commander. 

J'ai jeté un œil au code et pense avoir trouvé ce qui pose problème : dans la classe FreeboxAPI la fonction getTiles autour de la ligne 289 on a ça :

` case "int":
	foreach(str_split($Commande['ui']['access']) as $access){
	     if($access = "r"){
                    $Tile->AddCommande($Commande['label'],$Commande['ep_id'],"info",'numeric');
	            $Tile->checkAndUpdateCmd($Commande['ep_id'],$Commande['value']);
		}
		if($access = "w"){
                      $Tile->AddCommande($Commande['label'],$Commande['ep_id'],"action",'slider');
		}
	}
break;`

on est ici dans le cas avec $Commande['ui']['access'] qui vaut "rw" j'imagine donc que tu as mis un str_split ensuite pour dans ce cas créer à la fois une commande info numérique qui prendrait le retour d'état et une commande action slider pour envoyer la consigne (c'est comme ça que j'analyse en tout cas)

Le problème est donc qu'ensuite les 2 fonctions AddCommande vont être appelées successivement : 1 fois pour access = r et une fois pour access = w alors qu'elles prennent exactement les mêmes paramètres avec le même nom et même id. donc la première commande d'info est bien créée mais la seconde non puisque la fonction AddCommande détecte avec raison qu'elle existe déjà (même id).

Je voulais essayer de corriger quelque chose mais je ne sais pas comment tu vas vouloir gérer les id de ces 2 commandes côté jeedom pour une seul objet côté freebox. D'ailleurs faut il nécessairement 2 commandes ? Un slider peut il en même temps afficher la valeur de retour d'état ? Mes compétences en jeedom s'arrêtent à ce niveau du coup je ne touche à rien.

2 dernières petites choses : 
* pour les tests ce serait plutôt if($access == "r") au lieu d'un seul =
* et j'ai testé une bricole local avec une commande action slider seule pour la consigne d'ouverture et l'envoi échoue avec :
[2019-10-06 17:32:45][DEBUG] : Connexion sur la freebox pour Consigne douverture
[2019-10-06 17:32:45][DEBUG] : Connexion PUT sur la l'adresse mafreebox.free.fr/api/v6/home/endpoints/16/3/({"value":"8"})
[2019-10-06 17:32:45][DEBUG] : {   "error_code" : "not_updated",   "msg" : "JSON:0:0: wrong json_value type",   "success" : false }
[2019-10-06 17:32:45][DEBUG] : success KO
[2019-10-06 17:32:45][DEBUG] : error_code exists
[2019-10-06 17:32:45][DEBUG] : closing session

je pense qu'il y a un tout petit problème de formatage du json avec la valeur "8" qui part en chaine et pas en 8 (int).

Voilà, j'espère ne pas avoir été trop long.

Merci à toi pour le boulot en tout cas !

**Comment by mika-nt28** [comment]
Bien vue ils ont le même nom qui pose probleme
C'est corrigé pour la prochaine mise à jour

**Comment by durdur45** [comment]
J'ai regardé ta modif mais ça ne va pas aller car la fonction AddCommande fait ça :
`public function AddCommande($Name,$_logicalId,$Type="info", $SubType='binary', $Template='default', $unite='') {
$Commande = $this->getCmd(null,$_logicalId);
if (!is_object($Commande))`

Donc le getCmd ne cherche qu'avec le logicalId, modifier le nom de la commande n'a donc pas d'effet. 

Le seul moyen que je vois pour le moment est de mettre 2 logicalID différents pour l'info et la commande, mais comme de façon maline le logical_id est l'ep_id côté API Freebox et qu'il est donc utilisé lors de la mise à jour des données il faut bricoler un truc au niveau de la fonction de refresh et d'action

**Comment by mika-nt28** [comment]
Il ne faut pas mettre d'autre logicalId c'est le seul moyen d'identifier la commande de la freebox.
Je vais modifié la fonction addCommande pour qu'il cherche en fonction du type.

**Comment by durdur45** [comment]
C'est bien ce que je me disais aussi.
Ca va bien avec ta modif de addCommande, du coup les 2 commandes sont bien créées. Merci !

**Comment by mika-nt28** [comment]
Ok j'ai fait une restructuration sur la beta pour sortir la création de commande de  la class api
Il manquait aussi le lien entre la commande info et action
J'ai poussé la modification sur la beta du market

Peux tu verifier que tout fonctionnent encore
